let PanelConfig = {
  "left-side": {
    name: "Left Sidebar",
    type: "static",
    config: {
      show: true,
      float: false,
      scrollable: true,
      heigth: "full",
      width: "auto",
    },
    view: false,
  },
  "right-side": {
    name: "Right Sidebar",
    type: "static",
    config: {
      show: true,
      float: false,
      scrollable: true,
      heigth: "full",
      width: "auto",
    },
    view: false,
  },
  "left-pan": {
    name: "Left Panel",
    type: "float",
    config: {
      show: false,
      float: true,
      scrollable: true,
      heigth: "full",
      width: "auto",
    },
    view: false,
  },
  "right-pan": {
    name: "Right Panel",
    type: "float",
    config: {
      show: false,
      float: true,
      scrollable: true,
      heigth: "full",
      width: "auto",
    },
    view: false,
  },
  nav: {
    name: "Navbar",
    type: "static",
    config: {
      show: true,
      float: false,
      scrollable: false,
      heigth: "auto",
      width: "full",
    },
    view: false,
  },
  status: {
    name: "Status Panel",
    type: "static",
    config: {
      show: true,
      float: false,
      scrollable: false,
      heigth: "auto",
      width: "full",
    },
    view: false,
  },
  "bot-pan": {
    name: "Bottom Panel",
    type: "float",
    config: {
      show: false,
      float: true,
      scrollable: true,
      heigth: "auto",
      width: "full",
    },
    view: false,
  },
};
